### ISSUE TITLE
Why c-api-user

### ISSUE THREAD

**Issue by petr-tik** [FFIG/ffig-base#7]
Considering later docker images are built with root as user, I get the following error message on building ffig/web-base

Do we need c-api-user as a separate user?

```
docker build -t ffig/web-base .

The directory '/home/ffig/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled.
```

**Comment by ajbennieston** [comment]
It's generally considered a good idea to run services with the lowest set of privileges required. I don't think this changes inside a Docker container.

**Comment by jbcoe** [comment]
`c-api` is the old name we should call the user `ffig`.
