### ISSUE TITLE
less nesting and non-essential operations

### ISSUE THREAD

**Issue by petr-tik** [FFIG/ffig-base#9]
The amount of nesting inside the ffig main repo, where the dir to import is called ffig/ and the main script FFIG.py, makes it difficult to import the module from one directory of the docker container into another. I have managed to hack it by touching __init__.py files and sys.path.extend to start the ffig-explorer server. 

Also, creating a ffig repo without cloning the git repo to it looks premature. It would help to define how the ffig package will be imported and/or installed by other projects, so there is 1 clear method of doing it, rather than inconsistent set of hacks. 

I would recommend moving mkdir and chown out of ffig-base to the images, where code is cloned and ran. Also, let’s agree on a directory naming convention to make imports less confusing. 

/ffig_root_dir/full_ffig/ will hold ffig/ffig repo code
/ffig_root_dir/flask/ will hold ffig/rest-api code

Thoughts?

**Comment by ajbennieston** [comment]
Do we need to worry about this at the moment? Somewhere down the line, "production" use of FFIG would probably look something like

```
pip install ffig
```

then

```
import ffig
# etc.
```

**Comment by ajbennieston** [comment]
`/home/ffig` is the home directory for the `c-api-user` user. (We should probably rename the user to `ffig`, or the directory to `c-api-user`). We create a user in this image, so we should ensure that user has a home directory that is writable by them.

We don't have to clone the ffig software to that location, but it seems like a decent place to start. Ultimately, we'll use a package manager to install a packaged version of ffig.

Is there anything not addressed by the above? I think this can be closed...
